# Generated by Django 3.2.7 on 2021-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitNoteLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_note_length', models.CharField(default='1/4', max_length=50, unique=True, verbose_name='Unit Note Length')),
            ],
        ),
    ]
