# Generated by Django 3.2.7 on 2021-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='parts',
            field=models.IntegerField(default=1, verbose_name='Number of Parts'),
            preserve_default=False,
        ),
    ]
