# Generated by Django 3.2.7 on 2021-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_tune_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='parts',
            field=models.IntegerField(default=2, verbose_name='Number of Parts'),
        ),
    ]
