# Generated by Django 3.2.7 on 2021-09-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_abctune_unit_note_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abctunepiece',
            old_name='tune',
            new_name='abc_tune',
        ),
    ]
