# Generated by Django 3.2.7 on 2021-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_alter_tune_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='composer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tune_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Information about the tune'),
        ),
    ]
