# Generated by Django 3.2.7 on 2021-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0004_rename_tune_abctunepiece_abc_tune'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField(default=120, unique=True, verbose_name='Beats Per Minute')),
            ],
        ),
    ]
