# Generated by Django 3.2.7 on 2021-09-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0005_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='abctune',
            name='bpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunes.bpm', verbose_name='Unit Note Length'),
        ),
    ]
