# Generated by Django 3.2.7 on 2021-09-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0005_auto_20210908_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Abc Text')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.key', verbose_name='Key of Tune')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.tune', verbose_name='Tune')),
            ],
        ),
    ]
