# Generated by Django 3.2.7 on 2021-09-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0006_abctext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCTune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.key', verbose_name='Key of Tune')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.tune', verbose_name='Tune')),
            ],
        ),
        migrations.CreateModel(
            name='ABCTunePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_order', models.IntegerField(default=1, verbose_name='Part Number of Tune')),
                ('abc_piece', models.TextField(verbose_name='ABC text for part of Tune')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.abctune', verbose_name='ABC Tune')),
            ],
        ),
        migrations.DeleteModel(
            name='ABCText',
        ),
    ]
