# Generated by Django 3.2.7 on 2021-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0006_abctune_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpm',
            name='bpm',
            field=models.CharField(default=120, max_length=50, unique=True, verbose_name='Beats Per Minute'),
        ),
    ]
