# Generated by Django 3.2.7 on 2021-09-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0007_auto_20210909_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='abctunepiece',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Default Part?'),
        ),
        migrations.AddField(
            model_name='abctunepiece',
            name='part_title',
            field=models.CharField(blank=True, default='Part #', max_length=30, null=True, verbose_name='Title of Part'),
        ),
        migrations.AlterField(
            model_name='abctunepiece',
            name='part_order',
            field=models.IntegerField(default=1, verbose_name='Part Number'),
        ),
    ]
