# Generated by Django 3.2.7 on 2021-09-13 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0007_alter_bpm_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abctune',
            name='bpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunes.bpm', verbose_name='Beats Per Minute'),
        ),
        migrations.AlterField(
            model_name='bpm',
            name='bpm',
            field=models.CharField(default='1/4=120', max_length=50, unique=True, verbose_name='Beats Per Minute'),
        ),
    ]
