# Generated by Django 3.2.7 on 2021-09-21 18:51

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0008_auto_20210913_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abctunepiece',
            options={'ordering': ['part_order']},
        ),
        migrations.CreateModel(
            name='ReferenceAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.IntegerField(verbose_name='numbers of parts of tune')),
                ('beats_buffer', models.IntegerField(verbose_name='number of beats for buffer at beginning of reference recording')),
                ('beats_countin', models.IntegerField(verbose_name='number of count-in beats at beginning of reference recording')),
                ('beats_ending', models.IntegerField(verbose_name='number of beats at end of reference recording')),
                ('beats_per_part', models.IntegerField(verbose_name='number of beats per part')),
                ('audio_file', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/clayt/Documents/PythonFiles/40SessionTunes/DjangoApp/media/ReferenceAudio'))),
                ('description', models.TextField(verbose_name='description of reference audio')),
                ('bpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.bpm', verbose_name='Beats Per Minute of reference recording')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.meter', verbose_name='Meter')),
                ('tune_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.tunetype', verbose_name='Tune Type')),
            ],
        ),
    ]
