# Generated by Django 3.2.7 on 2021-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0009_auto_20210921_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceaudio',
            name='repeats',
            field=models.IntegerField(default=2, verbose_name='number of repeats of tune'),
            preserve_default=False,
        ),
    ]
