# Generated by Django 3.2.7 on 2021-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0011_auto_20210923_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceaudio',
            name='audio_file',
            field=models.FileField(upload_to='ReferenceAudio/', verbose_name='Reference Audio MP3 file'),
        ),
    ]
