name: Run Python Tests with FFMPEG
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ffmpeg
        run: |
          sudo apt-get install ffmpeg
          ffmpeg -version
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r DjangoApp/requirements.txt
      - name: Create env file
        run: |
          touch DjangoApp/.env
          echo "# Set environment variables" >> DjangoApp/.env
          echo "SECRET_KEY = ${{ secrets.SECRET_KEY }}" >> DjangoApp/.env
          echo "DEBUG = ${{ secrets.DEBUG }}" >> DjangoApp/.env
          echo "ALLOWED_HOSTS = ${{ secrets.ALLOWED_HOSTS }}" >> DjangoApp/.env
          cat DjangoApp/.env
      - name: Run tests with pytest
        working-directory: ./DjangoApp
        run: pytest 
